// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SkinSync.Data;

#nullable disable

namespace SkinSync.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SkinSync.Models.Entities.AiAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AgingRisk")
                        .HasColumnType("integer");

                    b.Property<string>("AiModel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("IssuesDetected")
                        .HasColumnType("jsonb");

                    b.Property<int>("OverallScore")
                        .HasColumnType("integer");

                    b.Property<string>("RawResponse")
                        .HasColumnType("jsonb");

                    b.Property<int?>("RecoveryCapacity")
                        .HasColumnType("integer");

                    b.Property<string>("RootCauses")
                        .HasColumnType("jsonb");

                    b.Property<int?>("SkinAge")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("completed");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int?>("UvDamage")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true);

                    b.ToTable("ai_analyses", null, t =>
                        {
                            t.HasCheckConstraint("ck_ai_analyses_aging_risk", "aging_risk IS NULL OR aging_risk BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_ai_analyses_overall_score", "overall_score BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_ai_analyses_recovery_capacity", "recovery_capacity IS NULL OR recovery_capacity BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_ai_analyses_status", "status IN ('pending', 'processing', 'completed', 'failed')");

                            t.HasCheckConstraint("ck_ai_analyses_uv_damage", "uv_damage IS NULL OR uv_damage BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("SkinSync.Models.Entities.AiAnalysisIssue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uuid");

                    b.Property<int?>("ConfidenceScore")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("IssueType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SeverityScore")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId");

                    b.HasIndex("IssueType");

                    b.HasIndex("AnalysisId", "IssueType");

                    b.ToTable("ai_analysis_issues", null, t =>
                        {
                            t.HasCheckConstraint("ck_ai_analysis_issues_confidence_score", "confidence_score IS NULL OR confidence_score BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_ai_analysis_issues_severity_score", "severity_score BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("SkinSync.Models.Entities.AiRecommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("RecommendationType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true);

                    b.ToTable("ai_recommendations", null, t =>
                        {
                            t.HasCheckConstraint("ck_ai_recommendations_priority", "priority BETWEEN 1 AND 5");

                            t.HasCheckConstraint("ck_ai_recommendations_type", "recommendation_type IN ('routine', 'product', 'lifestyle', 'warning', 'ingredient')");
                        });
                });

            modelBuilder.Entity("SkinSync.Models.Entities.AiChatConversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<DateTime>("LastMessageAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "LastMessageAt")
                        .IsDescending(false, true);

                    b.ToTable("ai_chat_conversations", (string)null);
                });

            modelBuilder.Entity("SkinSync.Models.Entities.AiChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "CreatedAt");

                    b.ToTable("ai_chat_messages", (string)null, t =>
                        {
                            t.HasCheckConstraint("ck_ai_chat_messages_role", "\"Role\" IN ('user', 'assistant', 'system')");
                        });
                });

            modelBuilder.Entity("SkinSync.Models.Entities.AiReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("MainFindings")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("NextPlan")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ProductFeedback")
                        .HasColumnType("text");

                    b.Property<string>("ProgressEvaluation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("RawAiResponse")
                        .HasColumnType("jsonb");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("RoutineFeedback")
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Warnings")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true);

                    b.ToTable("ai_reports", null, t =>
                        {
                            t.HasCheckConstraint("ck_ai_reports_progress_evaluation", "\"ProgressEvaluation\" IN ('improved', 'stable', 'worse', 'insufficient_data')");

                            t.HasCheckConstraint("ck_ai_reports_report_type", "\"ReportType\" IN ('weekly', 'monthly', 'after_analysis')");
                        });
                });

            modelBuilder.Entity("SkinSync.Models.Entities.AiUsageLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("CostEstimate")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<string>("FeatureName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UsedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "FeatureName", "UsedAt")
                        .IsDescending(false, false, true);

                    b.ToTable("ai_usage_logs", null, t =>
                        {
                            t.HasCheckConstraint("ck_ai_usage_logs_feature_name", "\"FeatureName\" IN ('skin_analysis', 'ai_chat', 'routine_generation', 'product_recommendation', 'ingredient_check', 'report_generation', 'conflict_check')");
                        });
                });

            modelBuilder.Entity("SkinSync.Models.Entities.DailyLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("DailyImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("EveningCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsIrritated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("MorningCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("SkinFeeling")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Date")
                        .IsUnique()
                        .IsDescending(false, true);

                    b.ToTable("daily_logs", null, t =>
                        {
                            t.HasCheckConstraint("ck_daily_logs_skin_feeling", "skin_feeling IS NULL OR skin_feeling IN ('good', 'normal', 'dry', 'oily', 'irritated', 'acne_flare', 'sensitive')");
                        });
                });

            modelBuilder.Entity("SkinSync.Models.Entities.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Benefit")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("NotSuitableFor")
                        .HasColumnType("jsonb");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("low");

                    b.Property<string>("SuitableSkinTypes")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ingredients", null, t =>
                        {
                            t.HasCheckConstraint("ck_ingredients_risk_level", "risk_level IN ('low', 'medium', 'high')");
                        });
                });

            modelBuilder.Entity("SkinSync.Models.Entities.IngredientConflictRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConflictingIngredient")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid?>("ConflictingIngredientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("Message")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("");

                    b.Property<string>("PrimaryIngredient")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid?>("PrimaryIngredientId")
                        .HasColumnType("uuid");

                    b.Property<string>("Recommendation")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("medium");

                    b.HasKey("Id");

                    b.HasIndex("ConflictingIngredientId");

                    b.HasIndex("PrimaryIngredient", "ConflictingIngredient")
                        .IsUnique()
                        .HasFilter("\"PrimaryIngredient\" IS NOT NULL AND \"ConflictingIngredient\" IS NOT NULL");

                    b.HasIndex("PrimaryIngredientId", "ConflictingIngredientId")
                        .IsUnique();

                    b.ToTable("ingredient_conflict_rules", null, t =>
                        {
                            t.HasCheckConstraint("ck_ingredient_conflict_rules_severity", "severity IN ('low', 'medium', 'high')");
                        });
                });

            modelBuilder.Entity("SkinSync.Models.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvoidForConcerns")
                        .HasColumnType("jsonb");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("VND");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Ingredient")
                        .HasColumnType("jsonb");

                    b.Property<string>("KeyIngredients")
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal?>("Rating")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("active");

                    b.Property<string>("SuitableSkinTypes")
                        .HasColumnType("jsonb");

                    b.Property<string>("TargetConcerns")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UsageGuide")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Brand");

                    b.HasIndex("Price");

                    b.HasIndex("Status", "Category");

                    b.ToTable("products", null, t =>
                        {
                            t.HasCheckConstraint("ck_products_price", "price >= 0");

                            t.HasCheckConstraint("ck_products_rating", "rating IS NULL OR rating BETWEEN 0 AND 5");

                            t.HasCheckConstraint("ck_products_status", "status IN ('active', 'out_of_stock', 'inactive')");
                        });
                });

            modelBuilder.Entity("SkinSync.Models.Entities.ProductIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Concentration")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductId", "IngredientId")
                        .IsUnique();

                    b.ToTable("product_ingredients", (string)null);
                });

            modelBuilder.Entity("SkinSync.Models.Entities.RegimenItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("Frequency")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Instruction")
                        .HasColumnType("text");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RegimenId")
                        .HasColumnType("uuid");

                    b.Property<string>("RoutineTime")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("StepOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("RegimenId", "RoutineTime", "StepOrder")
                        .IsUnique();

                    b.ToTable("regimen_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_regimen_items_routine_time", "routine_time IN ('Morning', 'Evening')");

                            t.HasCheckConstraint("ck_regimen_items_step_order", "step_order > 0");
                        });
                });

            modelBuilder.Entity("SkinSync.Models.Entities.Reminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("RoutineType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time without time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "RoutineType")
                        .IsUnique();

                    b.ToTable("reminders", null, t =>
                        {
                            t.HasCheckConstraint("ck_reminders_routine_type", "routine_type IN ('Morning', 'Evening')");
                        });
                });

            modelBuilder.Entity("SkinSync.Models.Entities.RoutineTracking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CompletedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("completed");

                    b.Property<Guid>("StepId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StepId");

                    b.HasIndex("UserId", "CompletedAt")
                        .IsDescending(false, true);

                    b.HasIndex("UserId", "StepId", "CompletedAt")
                        .IsDescending(false, false, true);

                    b.ToTable("routine_trackings", null, t =>
                        {
                            t.HasCheckConstraint("ck_routine_trackings_status", "status IN ('completed', 'skipped', 'missed')");
                        });
                });

            modelBuilder.Entity("SkinSync.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("PlanType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("free");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("user");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("active");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_plan_type", "\"PlanType\" IN ('free', 'premium')");

                            t.HasCheckConstraint("ck_users_role", "role IN ('user', 'admin', 'expert')");

                            t.HasCheckConstraint("ck_users_status", "status IN ('active', 'inactive', 'banned')");
                        });
                });

            modelBuilder.Entity("SkinSync.Models.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Allergies")
                        .HasColumnType("jsonb");

                    b.Property<int?>("BirthYear")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("MonthlyBudget")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("RoutinePreference")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SensitiveIngredients")
                        .HasColumnType("jsonb");

                    b.Property<int?>("SensitivityLevel")
                        .HasColumnType("integer");

                    b.Property<string>("SkinConcerns")
                        .HasColumnType("jsonb");

                    b.Property<string>("SkinGoals")
                        .HasColumnType("jsonb");

                    b.Property<string>("SkinType")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.ToTable("user_profiles", null, t =>
                        {
                            t.HasCheckConstraint("ck_user_profiles_age", "age IS NULL OR age >= 0");

                            t.HasCheckConstraint("ck_user_profiles_monthly_budget", "monthly_budget IS NULL OR monthly_budget >= 0");

                            t.HasCheckConstraint("ck_user_profiles_routine_preference", "\"RoutinePreference\" IS NULL OR \"RoutinePreference\" IN ('simple', 'balanced', 'advanced')");

                            t.HasCheckConstraint("ck_user_profiles_sensitivity_level", "sensitivity_level IS NULL OR sensitivity_level BETWEEN 1 AND 5");

                            t.HasCheckConstraint("ck_user_profiles_skin_type", "skin_type IS NULL OR skin_type IN ('oily', 'dry', 'combination', 'normal', 'sensitive', 'unknown')");
                        });
                });

            modelBuilder.Entity("SkinSync.Models.Entities.UserRegimen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AnalysisId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsCustom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasDefaultValue("Skin care routine");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("ai");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId");

                    b.HasIndex("UserId", "IsActive");

                    b.ToTable("user_regimens", null, t =>
                        {
                            t.HasCheckConstraint("ck_user_regimens_source", "source IN ('ai', 'user', 'expert', 'system')");
                        });
                });

            modelBuilder.Entity("SkinSync.Models.Entities.AiAnalysis", b =>
                {
                    b.HasOne("SkinSync.Models.Entities.User", "User")
                        .WithMany("Analyses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkinSync.Models.Entities.AiAnalysisIssue", b =>
                {
                    b.HasOne("SkinSync.Models.Entities.AiAnalysis", "Analysis")
                        .WithMany("AnalysisIssues")
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("SkinSync.Models.Entities.AiRecommendation", b =>
                {
                    b.HasOne("SkinSync.Models.Entities.AiAnalysis", "Analysis")
                        .WithMany("Recommendations")
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkinSync.Models.Entities.User", "User")
                        .WithMany("Recommendations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analysis");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkinSync.Models.Entities.AiChatConversation", b =>
                {
                    b.HasOne("SkinSync.Models.Entities.User", "User")
                        .WithMany("AiChatConversations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkinSync.Models.Entities.AiChatMessage", b =>
                {
                    b.HasOne("SkinSync.Models.Entities.AiChatConversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("SkinSync.Models.Entities.AiReport", b =>
                {
                    b.HasOne("SkinSync.Models.Entities.User", "User")
                        .WithMany("AiReports")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkinSync.Models.Entities.AiUsageLog", b =>
                {
                    b.HasOne("SkinSync.Models.Entities.User", "User")
                        .WithMany("AiUsageLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkinSync.Models.Entities.DailyLog", b =>
                {
                    b.HasOne("SkinSync.Models.Entities.User", "User")
                        .WithMany("DailyLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkinSync.Models.Entities.IngredientConflictRule", b =>
                {
                    b.HasOne("SkinSync.Models.Entities.Ingredient", "ConflictingIngredientEntity")
                        .WithMany("ConflictingConflictRules")
                        .HasForeignKey("ConflictingIngredientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SkinSync.Models.Entities.Ingredient", "PrimaryIngredientEntity")
                        .WithMany("PrimaryConflictRules")
                        .HasForeignKey("PrimaryIngredientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ConflictingIngredientEntity");

                    b.Navigation("PrimaryIngredientEntity");
                });

            modelBuilder.Entity("SkinSync.Models.Entities.ProductIngredient", b =>
                {
                    b.HasOne("SkinSync.Models.Entities.Ingredient", "Ingredient")
                        .WithMany("ProductIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkinSync.Models.Entities.Product", "Product")
                        .WithMany("ProductIngredients")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SkinSync.Models.Entities.RegimenItem", b =>
                {
                    b.HasOne("SkinSync.Models.Entities.Product", "Product")
                        .WithMany("RegimenItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkinSync.Models.Entities.UserRegimen", "Regimen")
                        .WithMany("Items")
                        .HasForeignKey("RegimenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Regimen");
                });

            modelBuilder.Entity("SkinSync.Models.Entities.Reminder", b =>
                {
                    b.HasOne("SkinSync.Models.Entities.User", "User")
                        .WithMany("Reminders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkinSync.Models.Entities.RoutineTracking", b =>
                {
                    b.HasOne("SkinSync.Models.Entities.RegimenItem", "Step")
                        .WithMany("Trackings")
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkinSync.Models.Entities.User", "User")
                        .WithMany("RoutineTrackings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Step");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkinSync.Models.Entities.UserProfile", b =>
                {
                    b.HasOne("SkinSync.Models.Entities.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("SkinSync.Models.Entities.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkinSync.Models.Entities.UserRegimen", b =>
                {
                    b.HasOne("SkinSync.Models.Entities.AiAnalysis", "Analysis")
                        .WithMany("Regimens")
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SkinSync.Models.Entities.User", "User")
                        .WithMany("Regimens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analysis");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkinSync.Models.Entities.AiAnalysis", b =>
                {
                    b.Navigation("AnalysisIssues");

                    b.Navigation("Recommendations");

                    b.Navigation("Regimens");
                });

            modelBuilder.Entity("SkinSync.Models.Entities.AiChatConversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("SkinSync.Models.Entities.Ingredient", b =>
                {
                    b.Navigation("ConflictingConflictRules");

                    b.Navigation("PrimaryConflictRules");

                    b.Navigation("ProductIngredients");
                });

            modelBuilder.Entity("SkinSync.Models.Entities.Product", b =>
                {
                    b.Navigation("ProductIngredients");

                    b.Navigation("RegimenItems");
                });

            modelBuilder.Entity("SkinSync.Models.Entities.RegimenItem", b =>
                {
                    b.Navigation("Trackings");
                });

            modelBuilder.Entity("SkinSync.Models.Entities.User", b =>
                {
                    b.Navigation("AiChatConversations");

                    b.Navigation("AiReports");

                    b.Navigation("AiUsageLogs");

                    b.Navigation("Analyses");

                    b.Navigation("DailyLogs");

                    b.Navigation("Profile");

                    b.Navigation("Recommendations");

                    b.Navigation("Regimens");

                    b.Navigation("Reminders");

                    b.Navigation("RoutineTrackings");
                });

            modelBuilder.Entity("SkinSync.Models.Entities.UserRegimen", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
