// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SkinSync.Data;

#nullable disable

namespace SkinSync.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SkinSync.Models.Entities.AiChatConversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<DateTime>("LastMessageAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "LastMessageAt")
                        .IsDescending(false, true);

                    b.ToTable("ai_chat_conversations", (string)null);
                });

            modelBuilder.Entity("SkinSync.Models.Entities.AiChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "CreatedAt");

                    b.ToTable("ai_chat_messages", null, t =>
                        {
                            t.HasCheckConstraint("ck_ai_chat_messages_role", "\"Role\" IN ('user', 'assistant', 'system')");
                        });
                });

            modelBuilder.Entity("SkinSync.Models.Entities.AiUsageLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("CostEstimate")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<string>("FeatureName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UsedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "FeatureName", "UsedAt")
                        .IsDescending(false, false, true);

                    b.ToTable("ai_usage_logs", null, t =>
                        {
                            t.HasCheckConstraint("ck_ai_usage_logs_feature_name", "\"FeatureName\" IN ('skin_analysis', 'skin_progress_analysis', 'skin_progress_compare', 'skin_progress_report', 'ai_chat', 'routine_generation', 'product_recommendation', 'ingredient_check', 'report_generation', 'conflict_check', 'smart_reminder', 'progress_entry')");
                        });
                });

            modelBuilder.Entity("SkinSync.Models.Entities.DailyLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AcneLevel")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("DailyImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int?>("DrynessLevel")
                        .HasColumnType("integer");

                    b.Property<bool>("EveningCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int?>("HydrationLevel")
                        .HasColumnType("integer");

                    b.Property<int?>("IrritationLevel")
                        .HasColumnType("integer");

                    b.Property<bool>("IsIrritated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("MorningCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int?>("RednessLevel")
                        .HasColumnType("integer");

                    b.Property<string>("SkinFeeling")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Date")
                        .IsUnique()
                        .IsDescending(false, true);

                    b.ToTable("daily_logs", null, t =>
                        {
                            t.HasCheckConstraint("ck_daily_logs_acne_level", "\"AcneLevel\" IS NULL OR \"AcneLevel\" BETWEEN 0 AND 5");

                            t.HasCheckConstraint("ck_daily_logs_dryness_level", "\"DrynessLevel\" IS NULL OR \"DrynessLevel\" BETWEEN 0 AND 5");

                            t.HasCheckConstraint("ck_daily_logs_hydration_level", "\"HydrationLevel\" IS NULL OR \"HydrationLevel\" BETWEEN 0 AND 5");

                            t.HasCheckConstraint("ck_daily_logs_irritation_level", "\"IrritationLevel\" IS NULL OR \"IrritationLevel\" BETWEEN 0 AND 5");

                            t.HasCheckConstraint("ck_daily_logs_redness_level", "\"RednessLevel\" IS NULL OR \"RednessLevel\" BETWEEN 0 AND 5");

                            t.HasCheckConstraint("ck_daily_logs_skin_feeling", "skin_feeling IS NULL OR skin_feeling IN ('good', 'normal', 'dry', 'oily', 'irritated', 'acne_flare', 'sensitive')");
                        });
                });

            modelBuilder.Entity("SkinSync.Models.Entities.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Benefit")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("NotSuitableFor")
                        .HasColumnType("jsonb");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("low");

                    b.Property<string>("SuitableSkinTypes")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ingredients", null, t =>
                        {
                            t.HasCheckConstraint("ck_ingredients_risk_level", "risk_level IN ('low', 'medium', 'high')");
                        });
                });

            modelBuilder.Entity("SkinSync.Models.Entities.IngredientConflictRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConflictingIngredient")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid?>("ConflictingIngredientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("Message")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("");

                    b.Property<string>("PrimaryIngredient")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid?>("PrimaryIngredientId")
                        .HasColumnType("uuid");

                    b.Property<string>("Recommendation")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("medium");

                    b.HasKey("Id");

                    b.HasIndex("ConflictingIngredientId");

                    b.HasIndex("PrimaryIngredient", "ConflictingIngredient")
                        .IsUnique()
                        .HasFilter("\"PrimaryIngredient\" IS NOT NULL AND \"ConflictingIngredient\" IS NOT NULL");

                    b.HasIndex("PrimaryIngredientId", "ConflictingIngredientId")
                        .IsUnique();

                    b.ToTable("ingredient_conflict_rules", null, t =>
                        {
                            t.HasCheckConstraint("ck_ingredient_conflict_rules_severity", "severity IN ('low', 'medium', 'high')");
                        });
                });

            modelBuilder.Entity("SkinSync.Models.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvoidForConcerns")
                        .HasColumnType("jsonb");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("VND");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Ingredient")
                        .HasColumnType("jsonb");

                    b.Property<string>("KeyIngredients")
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal?>("Rating")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("active");

                    b.Property<string>("SuitableSkinTypes")
                        .HasColumnType("jsonb");

                    b.Property<string>("TargetConcerns")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UsageGuide")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Brand");

                    b.HasIndex("Price");

                    b.HasIndex("Status", "Category");

                    b.ToTable("products", null, t =>
                        {
                            t.HasCheckConstraint("ck_products_price", "price >= 0");

                            t.HasCheckConstraint("ck_products_rating", "rating IS NULL OR rating BETWEEN 0 AND 5");

                            t.HasCheckConstraint("ck_products_status", "status IN ('active', 'out_of_stock', 'inactive')");
                        });
                });

            modelBuilder.Entity("SkinSync.Models.Entities.ProductIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Concentration")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductId", "IngredientId")
                        .IsUnique();

                    b.ToTable("product_ingredients", (string)null);
                });

            modelBuilder.Entity("SkinSync.Models.Entities.RegimenItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("Frequency")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Instruction")
                        .HasColumnType("text");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RegimenId")
                        .HasColumnType("uuid");

                    b.Property<string>("RoutineTime")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("StepOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("RegimenId", "RoutineTime", "StepOrder")
                        .IsUnique();

                    b.ToTable("regimen_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_regimen_items_routine_time", "routine_time IN ('morning', 'evening')");

                            t.HasCheckConstraint("ck_regimen_items_step_order", "step_order > 0");
                        });
                });

            modelBuilder.Entity("SkinSync.Models.Entities.Reminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("daily");

                    b.Property<bool>("IsAdaptive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Priority")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("medium");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<string>("RoutineType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time without time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "RoutineType")
                        .IsUnique();

                    b.ToTable("reminders", null, t =>
                        {
                            t.HasCheckConstraint("ck_reminders_priority", "\"Priority\" IN ('low', 'medium', 'high')");

                            t.HasCheckConstraint("ck_reminders_routine_type", "routine_type IN ('morning', 'evening')");
                        });
                });

            modelBuilder.Entity("SkinSync.Models.Entities.RoutineTracking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("RoutineTime")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("completed");

                    b.Property<Guid>("StepId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("TrackingDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StepId");

                    b.HasIndex("UserId", "TrackingDate")
                        .IsDescending(false, true);

                    b.HasIndex("UserId", "RoutineTime", "TrackingDate")
                        .IsDescending(false, false, true);

                    b.HasIndex("UserId", "StepId", "TrackingDate")
                        .IsUnique();

                    b.ToTable("routine_trackings", null, t =>
                        {
                            t.HasCheckConstraint("ck_routine_trackings_routine_time", "\"RoutineTime\" IN ('morning', 'evening')");

                            t.HasCheckConstraint("ck_routine_trackings_status", "status IN ('completed', 'skipped', 'missed')");
                        });
                });

            modelBuilder.Entity("SkinSync.Models.Entities.SkinPhotoComparison", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AfterAnalysisId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AfterPhotoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BeforeAnalysisId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BeforePhotoId")
                        .HasColumnType("uuid");

                    b.Property<string>("ComparisonSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConfidenceNote")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("Improvements")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("ProgressStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("insufficient_data");

                    b.Property<string>("Recommendations")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("ScoreChanges")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("StableAreas")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("WorsenedAreas")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.HasKey("Id");

                    b.HasIndex("AfterAnalysisId");

                    b.HasIndex("AfterPhotoId");

                    b.HasIndex("BeforeAnalysisId");

                    b.HasIndex("BeforePhotoId", "AfterPhotoId")
                        .IsUnique();

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true);

                    b.ToTable("skin_photo_comparisons", null, t =>
                        {
                            t.HasCheckConstraint("ck_skin_photo_comparisons_progress_status", "\"ProgressStatus\" IN ('improved', 'stable', 'worse', 'mixed', 'insufficient_data')");
                        });
                });

            modelBuilder.Entity("SkinSync.Models.Entities.SkinProgressAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AcneScore")
                        .HasColumnType("integer");

                    b.Property<string>("AiModel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AiSummary")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<int>("DarkSpotScore")
                        .HasColumnType("integer");

                    b.Property<string>("DetectedConcerns")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<DateTime?>("DiscardedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DrynessScore")
                        .HasColumnType("integer");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("HydrationLevel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("unknown");

                    b.Property<string>("OilinessLevel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("unknown");

                    b.Property<int>("OilinessScore")
                        .HasColumnType("integer");

                    b.Property<int>("OverallScore")
                        .HasColumnType("integer");

                    b.Property<string>("ParsedAiResponse")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("PhotoId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductSuggestions")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("RawAiResponse")
                        .HasColumnType("jsonb");

                    b.Property<string>("Recommendations")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<int>("RednessScore")
                        .HasColumnType("integer");

                    b.Property<string>("RiskFlags")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("RoutineSuggestions")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("SafetyNotes")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<int>("SensitivityScore")
                        .HasColumnType("integer");

                    b.Property<string>("SkinTypeEstimate")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("unknown");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("pending");

                    b.Property<int>("TextureScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PhotoId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true);

                    b.ToTable("skin_progress_analyses", null, t =>
                        {
                            t.HasCheckConstraint("ck_skin_progress_analyses_acne_score", "\"AcneScore\" BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_skin_progress_analyses_confidence_score", "\"ConfidenceScore\" IS NULL OR \"ConfidenceScore\" BETWEEN 0 AND 1");

                            t.HasCheckConstraint("ck_skin_progress_analyses_dark_spot_score", "\"DarkSpotScore\" BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_skin_progress_analyses_dryness_score", "\"DrynessScore\" BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_skin_progress_analyses_hydration", "\"HydrationLevel\" IN ('low', 'balanced', 'high', 'unknown')");

                            t.HasCheckConstraint("ck_skin_progress_analyses_oiliness", "\"OilinessLevel\" IN ('low', 'medium', 'high', 'only_t_zone', 'unknown')");

                            t.HasCheckConstraint("ck_skin_progress_analyses_oiliness_score", "\"OilinessScore\" BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_skin_progress_analyses_overall_score", "\"OverallScore\" BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_skin_progress_analyses_redness_score", "\"RednessScore\" BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_skin_progress_analyses_sensitivity_score", "\"SensitivityScore\" BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_skin_progress_analyses_skin_type", "\"SkinTypeEstimate\" IN ('oily', 'dry', 'combination', 'normal', 'sensitive', 'unknown')");

                            t.HasCheckConstraint("ck_skin_progress_analyses_status", "\"Status\" IN ('pending', 'processing', 'completed', 'failed', 'discarded')");

                            t.HasCheckConstraint("ck_skin_progress_analyses_texture_score", "\"TextureScore\" BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("SkinSync.Models.Entities.SkinProgressPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("FaceAngle")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("unknown");

                    b.Property<string>("ImageMetadataJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("LightingCondition")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("unknown");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<DateOnly>("PhotoDate")
                        .HasColumnType("date");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("unknown");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TimeOfDay")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("unknown");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "PhotoDate")
                        .IsDescending(false, true);

                    b.ToTable("skin_progress_photos", null, t =>
                        {
                            t.HasCheckConstraint("ck_skin_progress_photos_face_angle", "\"FaceAngle\" IN ('front', 'left', 'right', 'unknown')");

                            t.HasCheckConstraint("ck_skin_progress_photos_lighting_condition", "\"LightingCondition\" IN ('good', 'medium', 'poor', 'unknown')");

                            t.HasCheckConstraint("ck_skin_progress_photos_source", "\"Source\" IN ('dashboard', 'ai_hub', 'progress', 'onboarding', 'unknown')");

                            t.HasCheckConstraint("ck_skin_progress_photos_time_of_day", "\"TimeOfDay\" IN ('morning', 'afternoon', 'night', 'unknown')");
                        });
                });

            modelBuilder.Entity("SkinSync.Models.Entities.SkinProgressReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("MainFindings")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("NextSuggestions")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<DateOnly?>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("PeriodStart")
                        .HasColumnType("date");

                    b.Property<string>("PeriodType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ProductFeedback")
                        .HasColumnType("text");

                    b.Property<string>("ProgressStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("insufficient_data");

                    b.Property<string>("RawAiResponse")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("RelatedAnalysisId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReportCategory")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("progress_timeline");

                    b.Property<string>("RoutineFeedback")
                        .HasColumnType("text");

                    b.Property<string>("ScoreChanges")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("system");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RelatedAnalysisId");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true);

                    b.HasIndex("UserId", "ReportCategory", "PeriodType", "PeriodStart", "PeriodEnd", "RelatedAnalysisId")
                        .IsUnique();

                    b.ToTable("skin_progress_reports", null, t =>
                        {
                            t.HasCheckConstraint("ck_skin_progress_reports_after_analysis_related_analysis", "\"ReportCategory\" <> 'after_analysis' OR \"RelatedAnalysisId\" IS NOT NULL");

                            t.HasCheckConstraint("ck_skin_progress_reports_period_type", "\"PeriodType\" IS NULL OR \"PeriodType\" IN ('weekly', 'monthly', 'yearly', 'custom')");

                            t.HasCheckConstraint("ck_skin_progress_reports_progress_status", "\"ProgressStatus\" IN ('improved', 'stable', 'worse', 'mixed', 'insufficient_data')");

                            t.HasCheckConstraint("ck_skin_progress_reports_progress_timeline_period", "\"ReportCategory\" <> 'progress_timeline' OR (\"PeriodType\" IS NOT NULL AND \"PeriodStart\" IS NOT NULL AND \"PeriodEnd\" IS NOT NULL)");

                            t.HasCheckConstraint("ck_skin_progress_reports_report_category", "\"ReportCategory\" IN ('progress_timeline', 'after_analysis', 'routine_feedback', 'product_feedback', 'general_summary')");

                            t.HasCheckConstraint("ck_skin_progress_reports_source", "\"Source\" IN ('dashboard', 'ai_hub', 'progress', 'onboarding', 'system')");
                        });
                });

            modelBuilder.Entity("SkinSync.Models.Entities.SubscriptionPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BillingPeriod")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("monthly");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("VND");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("subscription_plans", null, t =>
                        {
                            t.HasCheckConstraint("ck_subscription_plans_billing_period", "\"BillingPeriod\" IN ('monthly')");

                            t.HasCheckConstraint("ck_subscription_plans_code", "\"Code\" IN ('free', 'plus', 'premium')");

                            t.HasCheckConstraint("ck_subscription_plans_price", "\"Price\" >= 0");
                        });
                });

            modelBuilder.Entity("SkinSync.Models.Entities.SubscriptionPlanFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AllowedValues")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("FeatureKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int?>("MonthlyLimit")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasDefaultValue("usage");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PlanId", "FeatureKey")
                        .IsUnique();

                    b.ToTable("subscription_plan_features", null, t =>
                        {
                            t.HasCheckConstraint("ck_subscription_plan_features_limit", "\"MonthlyLimit\" IS NULL OR \"MonthlyLimit\" >= 0");
                        });
                });

            modelBuilder.Entity("SkinSync.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("PlanType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("free");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("user");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("active");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_plan_type", "\"PlanType\" IN ('free', 'plus', 'premium')");

                            t.HasCheckConstraint("ck_users_role", "role IN ('user', 'admin', 'expert')");

                            t.HasCheckConstraint("ck_users_status", "status IN ('active', 'inactive', 'banned')");
                        });
                });

            modelBuilder.Entity("SkinSync.Models.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Allergies")
                        .HasColumnType("jsonb");

                    b.Property<int?>("BirthYear")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("MonthlyBudget")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("RoutinePreference")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SensitiveIngredients")
                        .HasColumnType("jsonb");

                    b.Property<int?>("SensitivityLevel")
                        .HasColumnType("integer");

                    b.Property<string>("SkinConcerns")
                        .HasColumnType("jsonb");

                    b.Property<string>("SkinGoals")
                        .HasColumnType("jsonb");

                    b.Property<string>("SkinType")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.ToTable("user_profiles", null, t =>
                        {
                            t.HasCheckConstraint("ck_user_profiles_age", "age IS NULL OR age >= 0");

                            t.HasCheckConstraint("ck_user_profiles_monthly_budget", "monthly_budget IS NULL OR monthly_budget >= 0");

                            t.HasCheckConstraint("ck_user_profiles_routine_preference", "\"RoutinePreference\" IS NULL OR \"RoutinePreference\" IN ('simple', 'balanced', 'advanced')");

                            t.HasCheckConstraint("ck_user_profiles_sensitivity_level", "sensitivity_level IS NULL OR sensitivity_level BETWEEN 1 AND 5");

                            t.HasCheckConstraint("ck_user_profiles_skin_type", "skin_type IS NULL OR skin_type IN ('oily', 'dry', 'combination', 'normal', 'sensitive', 'unknown')");
                        });
                });

            modelBuilder.Entity("SkinSync.Models.Entities.UserRegimen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsCustom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasDefaultValue("Skin care routine");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("ai");

                    b.Property<Guid?>("SourceAnalysisId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SourceAnalysisId");

                    b.HasIndex("UserId", "IsActive");

                    b.ToTable("user_regimens", null, t =>
                        {
                            t.HasCheckConstraint("ck_user_regimens_source", "source IN ('ai', 'user', 'expert', 'system')");
                        });
                });

            modelBuilder.Entity("SkinSync.Models.Entities.UserSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BillingPeriod")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("monthly");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("VND");

                    b.Property<DateTime?>("EndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PricePaid")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("active");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("UserId", "StartedAt")
                        .IsDescending(false, true);

                    b.HasIndex("UserId", "Status");

                    b.ToTable("user_subscriptions", null, t =>
                        {
                            t.HasCheckConstraint("ck_user_subscriptions_status", "\"Status\" IN ('active', 'canceled', 'expired')");
                        });
                });

            modelBuilder.Entity("SkinSync.Models.Entities.AiChatConversation", b =>
                {
                    b.HasOne("SkinSync.Models.Entities.User", "User")
                        .WithMany("AiChatConversations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkinSync.Models.Entities.AiChatMessage", b =>
                {
                    b.HasOne("SkinSync.Models.Entities.AiChatConversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("SkinSync.Models.Entities.AiUsageLog", b =>
                {
                    b.HasOne("SkinSync.Models.Entities.User", "User")
                        .WithMany("AiUsageLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkinSync.Models.Entities.DailyLog", b =>
                {
                    b.HasOne("SkinSync.Models.Entities.User", "User")
                        .WithMany("DailyLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkinSync.Models.Entities.IngredientConflictRule", b =>
                {
                    b.HasOne("SkinSync.Models.Entities.Ingredient", "ConflictingIngredientEntity")
                        .WithMany("ConflictingConflictRules")
                        .HasForeignKey("ConflictingIngredientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SkinSync.Models.Entities.Ingredient", "PrimaryIngredientEntity")
                        .WithMany("PrimaryConflictRules")
                        .HasForeignKey("PrimaryIngredientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ConflictingIngredientEntity");

                    b.Navigation("PrimaryIngredientEntity");
                });

            modelBuilder.Entity("SkinSync.Models.Entities.ProductIngredient", b =>
                {
                    b.HasOne("SkinSync.Models.Entities.Ingredient", "Ingredient")
                        .WithMany("ProductIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkinSync.Models.Entities.Product", "Product")
                        .WithMany("ProductIngredients")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SkinSync.Models.Entities.RegimenItem", b =>
                {
                    b.HasOne("SkinSync.Models.Entities.Product", "Product")
                        .WithMany("RegimenItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkinSync.Models.Entities.UserRegimen", "Regimen")
                        .WithMany("Items")
                        .HasForeignKey("RegimenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Regimen");
                });

            modelBuilder.Entity("SkinSync.Models.Entities.Reminder", b =>
                {
                    b.HasOne("SkinSync.Models.Entities.User", "User")
                        .WithMany("Reminders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkinSync.Models.Entities.RoutineTracking", b =>
                {
                    b.HasOne("SkinSync.Models.Entities.RegimenItem", "Step")
                        .WithMany("Trackings")
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkinSync.Models.Entities.User", "User")
                        .WithMany("RoutineTrackings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Step");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkinSync.Models.Entities.SkinPhotoComparison", b =>
                {
                    b.HasOne("SkinSync.Models.Entities.SkinProgressAnalysis", "AfterAnalysis")
                        .WithMany()
                        .HasForeignKey("AfterAnalysisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkinSync.Models.Entities.SkinProgressPhoto", "AfterPhoto")
                        .WithMany()
                        .HasForeignKey("AfterPhotoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkinSync.Models.Entities.SkinProgressAnalysis", "BeforeAnalysis")
                        .WithMany()
                        .HasForeignKey("BeforeAnalysisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkinSync.Models.Entities.SkinProgressPhoto", "BeforePhoto")
                        .WithMany()
                        .HasForeignKey("BeforePhotoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkinSync.Models.Entities.User", "User")
                        .WithMany("SkinPhotoComparisons")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AfterAnalysis");

                    b.Navigation("AfterPhoto");

                    b.Navigation("BeforeAnalysis");

                    b.Navigation("BeforePhoto");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkinSync.Models.Entities.SkinProgressAnalysis", b =>
                {
                    b.HasOne("SkinSync.Models.Entities.SkinProgressPhoto", "Photo")
                        .WithMany("Analyses")
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkinSync.Models.Entities.User", "User")
                        .WithMany("SkinProgressAnalyses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Photo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkinSync.Models.Entities.SkinProgressPhoto", b =>
                {
                    b.HasOne("SkinSync.Models.Entities.User", "User")
                        .WithMany("SkinProgressPhotos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkinSync.Models.Entities.SkinProgressReport", b =>
                {
                    b.HasOne("SkinSync.Models.Entities.SkinProgressAnalysis", "RelatedAnalysis")
                        .WithMany()
                        .HasForeignKey("RelatedAnalysisId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SkinSync.Models.Entities.User", "User")
                        .WithMany("SkinProgressReports")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RelatedAnalysis");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkinSync.Models.Entities.SubscriptionPlanFeature", b =>
                {
                    b.HasOne("SkinSync.Models.Entities.SubscriptionPlan", "Plan")
                        .WithMany("Features")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("SkinSync.Models.Entities.UserProfile", b =>
                {
                    b.HasOne("SkinSync.Models.Entities.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("SkinSync.Models.Entities.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkinSync.Models.Entities.UserRegimen", b =>
                {
                    b.HasOne("SkinSync.Models.Entities.SkinProgressAnalysis", "SourceAnalysis")
                        .WithMany()
                        .HasForeignKey("SourceAnalysisId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SkinSync.Models.Entities.User", "User")
                        .WithMany("Regimens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceAnalysis");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkinSync.Models.Entities.UserSubscription", b =>
                {
                    b.HasOne("SkinSync.Models.Entities.SubscriptionPlan", "Plan")
                        .WithMany("UserSubscriptions")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkinSync.Models.Entities.User", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkinSync.Models.Entities.AiChatConversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("SkinSync.Models.Entities.Ingredient", b =>
                {
                    b.Navigation("ConflictingConflictRules");

                    b.Navigation("PrimaryConflictRules");

                    b.Navigation("ProductIngredients");
                });

            modelBuilder.Entity("SkinSync.Models.Entities.Product", b =>
                {
                    b.Navigation("ProductIngredients");

                    b.Navigation("RegimenItems");
                });

            modelBuilder.Entity("SkinSync.Models.Entities.RegimenItem", b =>
                {
                    b.Navigation("Trackings");
                });

            modelBuilder.Entity("SkinSync.Models.Entities.SkinProgressPhoto", b =>
                {
                    b.Navigation("Analyses");
                });

            modelBuilder.Entity("SkinSync.Models.Entities.SubscriptionPlan", b =>
                {
                    b.Navigation("Features");

                    b.Navigation("UserSubscriptions");
                });

            modelBuilder.Entity("SkinSync.Models.Entities.User", b =>
                {
                    b.Navigation("AiChatConversations");

                    b.Navigation("AiUsageLogs");

                    b.Navigation("DailyLogs");

                    b.Navigation("Profile");

                    b.Navigation("Regimens");

                    b.Navigation("Reminders");

                    b.Navigation("RoutineTrackings");

                    b.Navigation("SkinPhotoComparisons");

                    b.Navigation("SkinProgressAnalyses");

                    b.Navigation("SkinProgressPhotos");

                    b.Navigation("SkinProgressReports");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("SkinSync.Models.Entities.UserRegimen", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
